# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1enjPpCUQZAY4Q11WYl0edSYAmkwxsG7X
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import pytesseract

def plot_rgb(img):
    plt.figure(figsize=(12,10))
    img = img.astype(np.uint8)
    return plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

park = cv2.imread("/content/park.jpeg")
plot_rgb(park);

doggy = cv2.imread("/content/doggy.jpg")
plot_rgb(doggy);

park_copy = park.copy()

park_copy[0:doggy.shape[0],100:100+doggy.shape[1]] = doggy

plot_rgb(park_copy);

height, width = park.shape[:2]
doggy = cv2.resize(doggy, (width//3, height//3))

park_copy = park.copy()
y_offset = int(height * 0.7)
x_offset = int(width * 0.7)
y1, y2 = y_offset, y_offset + doggy.shape[0]
x1, x2 = x_offset, x_offset + doggy.shape[1]
doggy = cv2.resize(doggy, (243, 162))
park_copy[y1:y2, x1:x2] = doggy

plot_rgb(park_copy);